Repository wireapp/wire-ios-sync-engine, pull requests merged in 2018-07, with the labels that each got.

#788 Update for changes in timestamp handling
  Cartfile
  Cartfile.resolved
  Source/Data Model/Conversation+Participants.swift
  Source/Synchronization/Strategies/TeamRegistrationStrategy.swift
  Source/Synchronization/Transcoders/ConversationStatusStrategy.swift
  Source/Synchronization/Transcoders/ZMConversationTranscoder.m
  Source/UserSession/CallStateObserver.swift
  Tests/Source/Calling/CallStateObserverTests.swift
  Tests/Source/Data Model/ZMConversation+Testing.m
  Tests/Source/E2EE/RequestStrategyTestBase.swift
  Tests/Source/E2EE/UserClientRequestStrategyTests.swift
  Tests/Source/Integration/CallingV3Tests.swift
  Tests/Source/Integration/ConnectionTests.m
  Tests/Source/Integration/ConversationTests+Participants.swift
  Tests/Source/Integration/ConversationTestsBase.m
  Tests/Source/Integration/ConversationsTests.m
  Tests/Source/Integration/SendAndReceiveMessagesTests.m
  Tests/Source/Integration/SlowSyncTests.m
  Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
  Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
  Tests/Source/Notifications/PushNotifications/ZMStoredLocalNotificationTests.swift
  Tests/Source/SessionManager/SessionManagerTests.swift
  Tests/Source/Synchronization/StoreUpdateEventTests.swift
  Tests/Source/Synchronization/Transcoders/ConversationStatusStrategyTests.swift
  Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
  Tests/Source/Synchronization/ZMHotFixDirectoryTests.swift
  Tests/Source/UserSession/ZMUserSessionTests.swift
Labels: API breaker, DO NOT MERGE

#794 Update for wire-ios-mocktransport api changes
  Cartfile.private
  Cartfile.resolved
  Tests/Source/E2EE/ConversationTests+OTR.m
Labels: API breaker

#800 Fix: crash in ZMConversationTranscoder - processDestructionTimerUpdate
  Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
Labels: DO NOT MERGE

#805 Include isNew field in shared identity detector result
  Source/Registration/SharedIdentity/SharedIdentitySessionRequestDetector.swift
  Source/Utility/Pasteboard.swift
  Tests/Source/MockPasteboard.swift
  Tests/Source/Registration/SharedIdentitySessionRequestDetectorTests.swift
Labels: API breaker

#797 Simplified push token registration and enabled verifying with backend
  Cartfile.resolved
  Source/Analytics/NotificationsTracker.swift
  Source/Data Model/Push Token/ZMPushToken.h
  Source/Data Model/Push Token/ZMPushToken.m
  Source/Public/WireSyncEngine.h
  Source/Public/ZMUserSession+Background.h
  Source/Public/ZMUserSession.h
  Source/Synchronization/Strategies/PushTokenStrategy.swift
  Source/Synchronization/ZMSyncStrategy.m
  Source/UserSession/ZMUserSession+Authentication.m
  Source/UserSession/ZMUserSession+Background.m
  Source/UserSession/ZMUserSession+Private.h
  Source/UserSession/ZMUserSession+Push.swift
  Source/UserSession/ZMUserSession.m
  Tests/Source/Data Model/ZMPushTokenTests.m
  Tests/Source/Integration/APNSTests.m
  Tests/Source/Integration/ConversationTestsBase.m
  Tests/Source/Integration/IntegrationTest.m
  Tests/Source/Integration/LoginFlowTests.m
  Tests/Source/Integration/PushNotificationTokenTests.swift
  Tests/Source/SessionManager/SessionManagerTests.swift
  Tests/Source/Synchronization/Strategies/PushTokenStrategyTests.swift
  Tests/Source/Synchronization/ZMHotFixTests.m
  Tests/Source/Synchronization/ZMHotFixTests.swift
  Tests/Source/UserSession/ZMUserSessionTests+PushNotifications.swift
  Tests/Source/UserSession/ZMUserSessionTests.m
  Tests/Source/UserSession/ZMUserSessionTestsBase.h
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: DO NOT MERGE

#813 Asynchronous fetching of images
  Cartfile
  Cartfile.resolved
  Source/Analytics/Analytics+Push.swift
  Source/Data Model/UserChangeInfo+UserSession.swift
  Source/Data Model/ZMUser+UserSession.m
  Source/Notifications/Push notifications/Notification Types/LocalNotificationType+Localization.swift
  Source/Public/WireSyncEngine.h
  Source/Public/ZMBareUser+UserSession.h
  Source/SessionManager/SessionManager.swift
  Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift
  Source/Synchronization/Strategies/SearchUserImageStrategy.swift
  Source/Synchronization/Strategies/UserClientRequestStrategy.swift
  Source/Synchronization/Strategies/UserImageAssetUpdateStrategy.swift
  Source/Synchronization/Strategies/UserImageStrategy.swift
  Source/UserSession/Search/SearchDirectory.swift
  Source/UserSession/Search/SearchDirectoryUserIDTable.swift
  Source/UserSession/Search/SearchResult+AddressBook.swift
  Source/UserSession/Search/SearchResult.swift
  Source/UserSession/Search/ZMSearchUser+UserSession.m
  Source/UserSession/ZMUserSession.m
  Tests/Source/Data Model/ServiceUserTests.swift
  Tests/Source/Data Model/ZMUserTests+UserSession.m
  Tests/Source/E2EE/ConversationTests+OTR.m
  Tests/Source/Integration/AvailabilityTests.swift
  Tests/Source/Integration/ConnectionTests.m
  Tests/Source/Integration/IntegrationTest+Search.swift
  Tests/Source/Integration/NotificationObservers.h
  Tests/Source/Integration/NotificationObservers.m
  Tests/Source/Integration/SearchTests.swift
  Tests/Source/Integration/UserHandleTests.swift
  Tests/Source/Integration/UserProfileImageV3Tests.swift
  Tests/Source/Integration/UserProfileTests.m
  Tests/Source/Integration/UserTests.m
  Tests/Source/SessionManager/SessionManagerTests.swift
  Tests/Source/Synchronization/Strategies/AddressBookUploadRequestStrategyTest.swift
  Tests/Source/Synchronization/Strategies/SearchUserImageStrategyTests.swift
  Tests/Source/Synchronization/Strategies/UserImageAssetUpdateStrategyTests.swift
  Tests/Source/Synchronization/Strategies/UserImageStrategyTests.swift
  Tests/Source/UserSession/SearchDirectoryTests.swift
  Tests/Source/UserSession/SearchDirectoryUserIDTableTests.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: API breaker
