Repository wireapp/wire-ios-sync-engine, pull requests merged in 2019-04, with the labels that each got.

#1004 Searching user for opening a user profile deep link
  Source/SessionManager/SessionManagerURLHandler.swift
  Source/UserSession/Search/SearchRequest.swift
  Source/UserSession/Search/SearchResult.swift
  Source/UserSession/Search/SearchTask.swift
  Tests/Source/SessionManager/SessionManagerURLHandlerTests.swift
Labels: API breaker

#1008 Hide notifications based on availability status
  Cartfile.resolved
  Source/Calling/CallKitDelegate.swift
  Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Calling.swift
  Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+Events.swift
  Source/SessionManager/SessionManager.swift
  Source/UserSession/CallStateObserver.swift
  Tests/Source/Notifications/PushNotifications/ZMLocalNotificationForTests_CallState.swift
Labels: Minor changes

#1012 Re-fetch team users after email field was introduced
  Source/Synchronization/ZMHotFixDirectory.m
Labels: Patch
