Repository wireapp/wire-ios-sync-engine, pull requests merged in 2020-04, with the labels that each got.

#1211 [Fix] SSO detection on iOS 13
  Source/Registration/Company/CompanyLoginRequestDetector.swift
  Source/Utility/Pasteboard.swift
  Tests/Source/MockPasteboard.swift
  Tests/Source/Registration/CompanyLoginRequestDetectorTests.swift
Labels: API breaker

#1218 [Chore] Remove address book upload
  Source/Synchronization/Strategies/AddressBookUploadRequestStrategy.swift
  Source/Synchronization/ZMSyncStrategy.m
  Source/UserSession/ZMUserSession+AddressBook.swift
  Tests/Source/MockAddressBook.swift
  Tests/Source/Registration/AddressBookTests.swift
  Tests/Source/Synchronization/Strategies/AddressBookUploadRequestStrategyTest.swift
  Tests/Source/UserSession/AddressBookSearchTests.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: API breaker

#1224 [Feature] AVS 5.6
  Cartfile
  Cartfile.resolved
  Source/Calling/AVSCallMember.swift
  Source/Calling/AVSWrapper+Handlers.swift
  Source/Calling/AVSWrapper.swift
  Source/Calling/CallParticipantSnapshot.swift
  Source/Calling/CallState.swift
  Source/Calling/NetworkQuality.swift
  Tests/Source/Calling/CallParticipantsSnapshotTests.swift
Labels: API breaker

#1228 [Fix] Missing system messages when member deleted
  Source/Synchronization/Transcoders/ZMConversationTranscoder.m
  Source/Synchronization/Transcoders/ZMConversationTranscoder.swift
  Tests/Source/Synchronization/Transcoders/ZMConversationTranscoderTests.m
Labels: Minor changes

#1138 [Chore] Migrate to Xcode 11.3
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Resources/Configurations/zmc-config/project-common.xcconfig
  Source/Calling/AVSWrapper.swift
  Tests/Source/E2EE/UserClientRequestStrategyTests.swift
  WireSyncEngine.xcodeproj/project.pbxproj
  WireSyncEngine.xcodeproj/xcshareddata/xcschemes/WireSyncEngine.xcscheme
Labels: DO NOT MERGE
