Repository wireapp/wire-ios-sync-engine, pull requests merged in 2020-03, with the labels that each got.

#1179 [Refactor] Replace ZMNewOTRMessage with NewOTRMessage
  Cartfile
  Cartfile.resolved
  Tests/Source/E2EE/ConversationTests+OTR.m
  Tests/Source/Integration/AvailabilityTests.swift
  Tests/Source/Integration/ConversationTests+OTR.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: Minor changes

#1180 [Fix] Renamed log tag to event-processing and improved the variable naming
  Source/Synchronization/Transcoders/ZMConversationTranscoder.m
Labels: Patch

#1183 [Refactor] Integrate AVS 5.6
  Cartfile
  Cartfile.resolved
  Source/Calling/AVSCallMember.swift
  Source/Calling/AVSWrapper+Handlers.swift
  Source/Calling/AVSWrapper.swift
  Source/Calling/CallParticipantSnapshot.swift
  Source/Calling/CallState.swift
  Source/Calling/NetworkQuality.swift
  Source/Calling/WireCallCenterV3+Events.swift
  Source/Calling/WireCallCenterV3+Notifications.swift
  Source/Calling/WireCallCenterV3.swift
  Tests/Source/Calling/CallParticipantsSnapshotTests.swift
  Tests/Source/Calling/VoiceChannelV3Tests.swift
  Tests/Source/Calling/WireCallCenterV3Tests.swift
Labels: API breaker

#1191 Bump Protos & Data Model
  Cartfile
  Cartfile.private
  Cartfile.resolved
Labels: chore

#1194 [Chore] Revert to AVS 5.5.6
  Cartfile
  Cartfile.resolved
  Source/Calling/AVSCallMember.swift
  Source/Calling/AVSWrapper+Handlers.swift
  Source/Calling/AVSWrapper.swift
  Source/Calling/CallParticipantSnapshot.swift
  Source/Calling/CallState.swift
  Source/Calling/NetworkQuality.swift
  Source/Calling/WireCallCenterV3+Events.swift
  Source/Calling/WireCallCenterV3+Notifications.swift
  Source/Calling/WireCallCenterV3.swift
  Tests/Source/Calling/CallParticipantsSnapshotTests.swift
  Tests/Source/Calling/VoiceChannelV3Tests.swift
  Tests/Source/Calling/WireCallCenterV3Tests.swift
Labels: API breaker
