Repository wireapp/wire-ios-sync-engine, pull requests merged in 2021-03, with the labels that each got.

#1350 chore: update Azure to Xcode 12
  Cartfile
  Cartfile.private
  Cartfile.resolved
Labels: DO NOT MERGE

#1413 [Feature] mute when answering call in group conversation
  Source/Calling/WireCallCenterV3.swift
  Tests/Source/Calling/WireCallCenterV3Tests.swift
Labels: Minor changes

#1416 [Refactor] Remove VerifyPasswordRequestStrategy and UserSessionVerifyPasswordInterface
  Source/Synchronization/Strategies/VerifyPasswordRequestStrategy.swift
  Source/Synchronization/StrategyDirectory.swift
  Source/UserSession/ZMUserSession+VerifyPassword.swift
  Tests/Source/Synchronization/Strategies/VerifyPasswordRequestStrategyTests.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: API breaker

#1411 [Fix]: Handle gracefully when device runs out of disk space
  Cartfile.resolved
  Source/SessionManager/LocalStoreProvider.swift
  Source/SessionManager/SessionManager.swift
  Tests/Source/Integration/IntegrationTest.swift
  Tests/Source/MessagingTest.m
  Tests/Source/SessionManager/SessionManagerTests.swift
Labels: API breaker
