Repository wireapp/wire-ios-sync-engine, pull requests merged in 2021-07, with the labels that each got.

#1482 Feature: xcframework
  Cartfile
  Cartfile.private
  Cartfile.resolved
  Resources/Configurations/zmc-config/ios.xcconfig
  Resources/Configurations/zmc-config/project-common.xcconfig
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: DO NOT MERGE

#1491 [Feature] Create a default value for the fileSharing feature
  Source/UserSession/ZMUserSession.swift
Labels: Feature request

#1492 [Refactor] Feature configs
  Cartfile
  Cartfile.resolved
  Source/SessionManager/SessionManager.swift
  Source/SessionManager/SessionManagerConfiguration.swift
  Source/UserSession/ZMUserSession.Configuration.swift
  Source/UserSession/ZMUserSession.swift
  Tests/Source/Integration/IntegrationTest.h
  Tests/Source/Integration/IntegrationTest.m
  Tests/Source/Integration/IntegrationTest.swift
  Tests/Source/SessionManager/SessionManagerConfigurationTests.swift
  Tests/Source/UserSession/ZMUserSessionTestsBase+ZMUserSessionConfiguration.swift
  Tests/Source/UserSession/ZMUserSessionTests_NetworkState.swift
  Tests/Source/Utility/ZMUserSession+DefaultConfiguration.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: API breaker
