Repository wireapp/wire-ios-sync-engine, pull requests merged in 2021-06, with the labels that each got.

#1435 dummy commit for testing zenkins release
  Tests/Source/Data Model/ServiceUserTests.swift
Labels: DO NOT MERGE

#1450 [Feature] Add an endpoint to join a conversation
  Cartfile.resolved
  Source/Data Model/Conversation+Join.swift
  Tests/Source/Integration/ConversationTests+Join.swift
  Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: Feature request

#1453 [Feature] Process the url action to join the conversation
  Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
  Source/UserSession/ZMUserSession.swift
  Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
Labels: Feature request

#1454 [Feature] Add a new endpoint GET conversation/join
  Source/Data Model/Conversation+Join.swift
  Source/SessionManager/PresentationDelegate.swift
  Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
  Tests/Source/Integration/ConversationTests+Join.swift
  Tests/Source/MockPresentationDelegate.swift
  Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
Labels: Feature request

#1458 [Feature] Join the conversation via deep link
  Cartfile.private
  Cartfile.resolved
  Source/Data Model/Conversation+Join.swift
  Source/DeepLink/URL+DeepLink.swift
  Source/SessionManager/PresentationDelegate.swift
  Source/SessionManager/URLActions.swift
  Source/UserSession/URLActionProcessors/DeepLinkURLActionProcessor.swift
  Source/UserSession/ZMUserSession.swift
  Tests/Source/Integration/ConversationTests+Join.swift
  Tests/Source/MockPresentationDelegate.swift
  Tests/Source/SessionManager/URLActionTests.swift
  Tests/Source/UserSession/DeepLinkURLActionProcessorTests.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: API breaker, Feature request

#1459 Rename for data modal renaming
  Cartfile
  Cartfile.resolved
  Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification+AvailabilityAlert.swift
  Source/Notifications/Push notifications/Notification Types/Content/ZMLocalNotification.swift
  Tests/Source/Data Model/ServiceUserTests.swift
  Tests/Source/Synchronization/Strategies/UserImageAssetUpdateStrategyTests.swift
Labels: DO NOT MERGE
