Repository wireapp/wire-ios-sync-engine, pull requests merged in 2021-11, with the labels that each got.

#1526 chore: Xcode13
  README.md
Labels: DO NOT MERGE

#1576 revert: Self-deleting messages SQSERVICES-1018
  Cartfile
  Cartfile.resolved
  Source/Analytics/Analytics+Push.swift
  Source/UserSession/ZMUserSession.swift
  Tests/Source/Integration/ConversationTests+Ephemeral.swift
  Tests/Source/Integration/ConversationTests+MessageTimer.swift
  Tests/Source/Integration/FileTransferTests+Swift.swift
  Tests/Source/Integration/LinkPreviewTests.swift
  Tests/Source/Integration/TextSearchTests.swift
  Tests/Source/Notifications/PushNotifications/LocalNotificationContentTypeTest.swift
  Tests/Source/Notifications/PushNotifications/LocalNotificationDispatcherTests.swift
  Tests/Source/Notifications/PushNotifications/ZMLocalNotificationTests_Message.swift
  Tests/Source/SessionManager/SessionManagerTests+Backup.swift
Labels: chore

#1571 chore: Fix SwiftLint warnings in Tests
  Tests/Source/UserSession/PushNotificationStatusTests.swift
  Tests/Source/UserSession/SearchDirectoryTests.swift
  Tests/Source/UserSession/SearchRequestTests.swift
  Tests/Source/UserSession/SearchResultTests.swift
  Tests/Source/UserSession/SearchTaskTests.swift
  Tests/Source/UserSession/SyncStatusTests.swift
  Tests/Source/UserSession/TeamInvitationStatusTests.swift
  Tests/Source/UserSession/TopConversationsDirectoryTests.swift
  Tests/Source/UserSession/UnauthenticatedSessionTests+DomainLookup.swift
  Tests/Source/UserSession/UnauthenticatedSessionTests+SSO.swift
  Tests/Source/UserSession/UnauthenticatedSessionTests.swift
  Tests/Source/UserSession/UserExpirationObserverTests.swift
  Tests/Source/UserSession/UserProfileImageUpdateStatusTests.swift
  Tests/Source/UserSession/UserProfileUpdateStatusTests.swift
  Tests/Source/UserSession/UserSessionGiphyRequestStateTests.swift
  Tests/Source/UserSession/ZMAuthenticationStatusTests.swift
  Tests/Source/UserSession/ZMCredentialsTests.swift
  Tests/Source/UserSession/ZMUserSessionTests+Authentication.swift
  Tests/Source/UserSession/ZMUserSessionTests+EncryptionAtRest.swift
  Tests/Source/UserSession/ZMUserSessionTests+FileRelocation.swift
  Tests/Source/UserSession/ZMUserSessionTests+PushNotifications.swift
  Tests/Source/UserSession/ZMUserSessionTests+Syncing.swift
  Tests/Source/UserSession/ZMUserSessionTests+Timers.swift
  Tests/Source/UserSession/ZMUserSessionTests.swift
  Tests/Source/UserSession/ZMUserSessionTestsBase+Calling.swift
  Tests/Source/UserSession/ZMUserSessionTests_NetworkState.swift
  Tests/Source/Utility/AnalyticsTests.swift
  Tests/Source/Utility/ApplicationMock.swift
  Tests/Source/Utility/DispatchQueueSerialAsyncTests.swift
  Tests/Source/Utility/OperationLoopNewRequestObserver.swift
  Tests/Source/Utility/PushRegistryMock.swift
  Tests/Source/Utility/UserNotificationCenterMock.swift
Labels: Fix PR Title 🤦‍♂️
