Repository wireapp/wire-ios-sync-engine, pull requests merged in 2022-04, with the labels that each got.

#1710 fix: crash when searching federated users FS-520
  Resources/Configurations/version.xcconfig
  Source/UserSession/Search/SearchDirectory.swift
  Source/UserSession/Search/SearchRequest.swift
  Source/UserSession/Search/SearchResult+AddressBook.swift
  Source/UserSession/Search/SearchResult.swift
  Source/UserSession/Search/SearchTask.swift
  Tests/Source/UserSession/SearchRequestTests.swift
  Tests/Source/UserSession/SearchResultTests.swift
  Tests/Source/UserSession/SearchTaskTests.swift
Labels: API breaker

#1707 test: Integration Tests for `guestLinkFeatureStatus` and `canGenerateGuestLink` SQSERVICES-1433
  Cartfile.private
  Cartfile.resolved
  Resources/Configurations/version.xcconfig
  Tests/Source/Integration/ConversationTests+Guests.swift
Labels: minor release

#1724 chore: release new version
  Resources/Configurations/version.xcconfig
  Source/Calling/WireCallCenterV3+Notifications.swift
Labels: Patch

#1725 fix: getting wrong short version string SQCORE-1289
  Resources/Configurations/version.xcconfig
  Resources/WireSyncEngine-ios-Info.plist
  Source/Synchronization/ZMHotFix.m
Labels: Patch
