Repository wireapp/wire-ios-sync-engine, pull requests merged in 2022-01, with the labels that each got.

#1625 feat: Add a new error to the WirelessLinkError enum SQSERVICES-1049
  Source/Data Model/Conversation+AccessMode.swift
  Tests/Source/Synchronization/ZMConversationAccessModeTests.swift
Labels: API breaker, Feature request

#1601 feat: Handle the new guest links feature config SQSERVICES-1049
  Resources/Configurations/version.xcconfig
  Source/Data Model/Conversation+AccessMode.swift
  Source/UserSession/ZMUserSession.swift
  Tests/Source/Synchronization/ZMConversationAccessModeTests.swift
Labels: Feature request

#1656 fix: calling not working on staging due to domain FS-357
  Resources/Configurations/version.xcconfig
  Source/Calling/AVSIdentifier/ZMConversation+AVSIdentifier.swift
  Source/Calling/AVSIdentifier/ZMUser+AVSIdentifier.swift
  Tests/Source/Calling/ZMConversation+AVSIdentifierTests.swift
  Tests/Source/Calling/ZMUser+AVSIdentifierTests.swift
  WireSyncEngine.xcodeproj/project.pbxproj
Labels: Patch

#1659 fix: calling tests failing due to MockUser IC-29
  Resources/Configurations/version.xcconfig
  Source/Calling/AVSIdentifier/ZMConversation+AVSIdentifier.swift
  Source/Calling/AVSIdentifier/ZMUser+AVSIdentifier.swift
Labels: Patch
